### ISSUE TITLE
S3 paths are raising ValueError: Invalid endpoint: s3.amazonaws.com

### ISSUE THREAD

**Issue by captify-ameszaros** [wanzysky/smart_path#2]
The `OSS_ENDPOINT` here:

https://github.com/wanzysky/smart_path/blob/3a4cd78a8487b4ead7e59763fbf7faa59b2ed77f/smart_path/__init__.py#L11

should be a url:

https://github.com/boto/botocore/blob/2264dada622de243c550070e7d509cf5a719f875/botocore/utils.py#L993

Therefore, the following would fix the default case: 

```python3
OSS_ENDPOINT="https://s3.amazonaws.com"
```

Pull request with the fix: 

https://github.com/wanzysky/smart_path/pull/1

**Comment by captify-ameszaros** [comment]
Since the pull request merged, I'm closing this issue.

**Comment by a-shkarupin** [comment]
@wanzysky could you please publish a version with a fix? The version which is published on pypi https://pypi.org/project/smart-path/#history doesn't have this fix.

**Comment by wanzysky** [comment]
Sure, I will upload it in couple of hours.

**Comment by wanzysky** [comment]
Done.
